language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.3.0

before_install:
  - 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'

install:
  - gem install bundler
  - bundle install --path vendor/bundle

before_script:
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:create db:schema:load db:test:prepare
